name: CI-CD Esteira Java com SonarCloud e Docker
# Este workflow realiza o build, testes, análise de código com SonarCloud e deploy de uma aplicação Java usando Maven e Docker.

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Desfazer shallow clone
        shell: bash
        run: git fetch --unshallow

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Permitir execução do mvnw
        shell: bash
        run: chmod +x ./mvnw
        working-directory: demo

      - name: Build com Maven
        shell: bash
        run: ./mvnw clean install
        working-directory: demo

      - name: Executar testes
        shell: bash
        run: ./mvnw test
        working-directory: demo

      - name: Criar projeto no SonarCloud via API
        shell: bash
        run: |
          curl -X POST "https://sonarcloud.io/api/projects/create" \
            -u "${SONAR_TOKEN}:" \
            -d "name=${{ github.repository_owner }}_${{ github.event.repository.name }}" \
            -d "project=${{ github.repository_owner }}_${{ github.event.repository.name }}" \
            -d "organization=${{ vars.ORGANIZATION_SONAR }}"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Análise SonarCloud
        shell: bash
        run: |
          ./mvnw org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar \
            -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }} \
            -Dsonar.organization=${{ vars.ORGANIZATION_SONAR }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${SONAR_TOKEN} \
            -Dsonar.branch.name=${{ github.ref_name }} \
            -Dsonar.verbose=true
        working-directory: demo
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Publicar artefato
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: demo-artifact
          path: demo/target/*.jar

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Permitir execução do mvnw
        shell: bash
        run: chmod +x ./mvnw
        working-directory: demo

      - name: Baixar artefato do build
        uses: actions/download-artifact@v4
        with:
          name: demo-artifact
          path: demo/target

      - name: Publicar no GitHub Packages (Maven)
        shell: bash
        run: |
          ./mvnw deploy -DskipTests --settings settings.xml \
            -DaltDeploymentRepository=github::https://maven.pkg.github.com/${{ github.repository }}
        working-directory: demo
        env:
          AUTHENTICATOR_G_TOKEN: ${{ secrets.AUTHENTICATOR_G_TOKEN }}

      - name: Login no GitHub Container Registry
        shell: bash
        run: echo "${{ secrets.AUTHENTICATOR_G_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build da imagem Docker
        shell: bash
        run: docker build -t ghcr.io/${{ github.repository }}/demo-app:latest .
        working-directory: demo

      - name: Push da imagem Docker
        shell: bash
        run: docker push ghcr.io/${{ github.repository }}/demo-app:latest